services:
  ladybug-explorer:
    image: ladybugdb/explorer:latest
    ports:
      - "8000:8000"
    volumes:
      - ./db.ladybug:/database/db.ladybug
    environment:
      MODE: READ_ONLY
      LADYBUG_FILE: db.ladybug
