# Copyright 2026 OpenTrace Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""OpenTrace CLI — index local codebases into a LadybugDB knowledge graph."""

from __future__ import annotations

import logging
import os
import signal
import threading
import time
from pathlib import Path

import click

# ---------------------------------------------------------------------------
# Database discovery
# ---------------------------------------------------------------------------

DB_NAME = "index.db"
OPENTRACE_DIR = ".opentrace"
_MAX_WALK_DEPTH = 10


def _find_git_root(start: Path) -> Path | None:
    """Find the nearest git repo root at or above *start*."""
    current = start.resolve()
    for _ in range(_MAX_WALK_DEPTH):
        if (current / ".git").exists():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    return None


def _is_under(path: Path, root: Path) -> bool:
    """Check if *path* is at or under *root*."""
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def _find_opentrace_dir(start: Path | None = None) -> Path | None:
    """Walk up from *start* looking for an existing ``.opentrace/`` directory.

    Security boundaries:
    - Stops at the git repo root (or filesystem root).
    - Rejects symlinks that resolve outside the boundary.
    - Caps upward traversal at ``_MAX_WALK_DEPTH`` levels.
    """
    if start is None:
        start = Path.cwd()
    start = start.resolve()

    git_root = _find_git_root(start)
    # Use git root as boundary only if start is inside it.
    boundary = git_root if git_root and _is_under(start, git_root) else Path(start.anchor)

    current = start
    for _ in range(_MAX_WALK_DEPTH):
        candidate = current / OPENTRACE_DIR
        if candidate.is_dir():
            resolved = candidate.resolve()
            # Reject if the resolved path escapes the repo boundary.
            if _is_under(resolved, boundary):
                return resolved
        # Stop at boundary or filesystem root.
        if current == boundary or current.parent == current:
            break
        current = current.parent

    return None


def find_db(start: Path | None = None) -> Path | None:
    """Walk up from *start* looking for ``.opentrace/index.db``.

    Security boundaries:
    - Stops at the git repo root (or filesystem root).
    - Rejects symlinks that resolve outside the boundary.
    - Caps upward traversal at ``_MAX_WALK_DEPTH`` levels.
    """
    ot_dir = _find_opentrace_dir(start)
    if ot_dir is not None:
        db_path = ot_dir / DB_NAME
        if db_path.exists():
            return db_path
    return None


def _resolve_db(db_path: str | None, *, must_exist: bool = False) -> str:
    """Return a database path from an explicit flag or auto-discovery.

    Raises ``click.UsageError`` if *must_exist* and no database is found.
    """
    if db_path is not None:
        p = Path(db_path)
        if must_exist and not p.exists():
            raise click.UsageError(f"Database not found: {db_path}")
        return str(p)

    found = find_db()
    if found is not None:
        return str(found)

    if must_exist:
        raise click.UsageError(
            f"No {OPENTRACE_DIR}/{DB_NAME} found. Run 'opentraceai index' first or pass --db explicitly."
        )

    # Default for index (write) — create in cwd.
    return str(Path.cwd() / OPENTRACE_DIR / DB_NAME)


_GITIGNORE_CONTENT = """\
# OpenTrace index data — generated by `opentraceai index`
*.db
*.db.wal
"""


def _ensure_gitignore(directory: Path) -> None:
    """Write a .gitignore into *directory* if one doesn't already exist."""
    gi = directory / ".gitignore"
    if not gi.exists():
        gi.write_text(_GITIGNORE_CONTENT)


@click.group(invoke_without_command=True)
@click.version_option(package_name="opentraceai")
@click.pass_context
def app(ctx: click.Context) -> None:
    """OpenTrace — map codebases into a knowledge graph."""
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


@app.command()
@click.argument("path", default=".", type=click.Path(exists=True, file_okay=False, resolve_path=True))
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help=f"Database path (default: ./{OPENTRACE_DIR}/{DB_NAME}).",
)
@click.option("--repo-id", default=None, help="Repository ID (defaults to directory name).")
@click.option("--batch-size", default=200, show_default=True, help="Items per batch.")
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def index(
    path: str,
    db_path: str | None,
    repo_id: str | None,
    batch_size: int,
    verbose: bool,
) -> None:
    """Index a local codebase into a LadybugDB knowledge graph."""
    _configure_logging(verbose)

    from opentrace_agent.pipeline import PipelineInput, run_pipeline
    from opentrace_agent.pipeline.adapters import GraphStoreAdapter
    from opentrace_agent.store import GraphStore

    root = Path(path)
    if repo_id is None:
        repo_id = root.name

    resolved_db = _resolve_db(db_path)
    db_dir = Path(resolved_db).parent
    db_dir.mkdir(parents=True, exist_ok=True)
    _ensure_gitignore(db_dir)

    # Write to a staging file so we don't contend with readers (MCP)
    # that hold an exclusive lock on the live database.
    staging_db = resolved_db + ".staging"

    click.echo(f"Opening staging database at {staging_db} ...")
    try:
        with GraphStore(staging_db) as graph_store:
            store = GraphStoreAdapter(graph_store, batch_size=batch_size)

            click.echo(f"Indexing {root} ...")
            t0 = time.monotonic()

            inp = PipelineInput(path=str(root), repo_id=repo_id)

            last_result = None
            for event in run_pipeline(inp, store=store):
                _print_event(event, verbose)
                if getattr(event, "result", None) is not None:
                    last_result = event.result

            elapsed = time.monotonic() - t0

            # Save index metadata.
            metadata = _collect_metadata(root, repo_id, elapsed, last_result)
            graph_store.save_metadata(metadata)

            # Flush pending batches; the GraphStore is closed by the
            # context manager on exit.
            store.flush()
    except BaseException:
        # Clean up the staging file on failure.
        Path(staging_db).unlink(missing_ok=True)
        raise

    # Atomically replace the live database.  Readers holding the old
    # file descriptor continue to see the previous data until they
    # detect the inode change and reopen.
    os.replace(staging_db, resolved_db)

    click.echo(f"Done in {elapsed:.1f}s.")


def _print_event(event: object, verbose: bool) -> None:
    """Print pipeline events to the terminal."""
    from opentrace_agent.pipeline import EventKind

    kind = getattr(event, "kind", None)
    message = getattr(event, "message", "")
    result = getattr(event, "result", None)

    if kind == EventKind.STAGE_START:
        click.echo(f"  {message}")
    elif kind == EventKind.STAGE_PROGRESS and verbose:
        detail = getattr(event, "detail", None)
        if detail:
            click.echo(f"    [{detail.current}/{detail.total}] {message}")
    elif kind == EventKind.STAGE_STOP:
        click.echo(f"  {message}")
    elif kind == EventKind.DONE and result:
        click.echo(
            f"  {result.nodes_created} nodes, "
            f"{result.relationships_created} relationships, "
            f"{result.files_processed} files, "
            f"{result.classes_extracted} classes, "
            f"{result.functions_extracted} functions"
        )
    elif kind == EventKind.ERROR:
        errors = getattr(event, "errors", [])
        click.echo(f"  Error: {message}", err=True)
        for err in errors or []:
            click.echo(f"    {err}", err=True)


def _collect_metadata(root: Path, repo_id: str | None, elapsed: float, result: object | None) -> dict[str, object]:
    """Gather index metadata from the repo and pipeline result.

    Keys use camelCase column names matching the proto-generated IndexMetadata
    schema so both Python and TypeScript consumers see the same shape.
    """
    from datetime import datetime, timezone

    meta: dict[str, object] = {
        "indexedAt": datetime.now(timezone.utc).isoformat(),
        "durationSeconds": round(elapsed, 2),
        "repoId": repo_id,
        "repoPath": str(root),
        "opentraceaiVersion": _get_version(),
    }

    # Git info — best-effort, non-fatal.
    try:
        import git

        repo = git.Repo(root, search_parent_directories=True)
        head = repo.head.commit
        meta["commitSha"] = head.hexsha
        meta["commitMessage"] = head.message.strip().split("\n", 1)[0]
        meta["branch"] = repo.active_branch.name if not repo.head.is_detached else None
        # Remote URL — prefer 'origin', fall back to first remote.
        if repo.remotes:
            remote = repo.remotes["origin"] if "origin" in repo.remotes else repo.remotes[0]
            meta["sourceUri"] = remote.url
    except Exception:
        pass

    # Pipeline result stats.
    if result is not None:
        _ATTR_MAP = {
            "nodes_created": "nodesCreated",
            "relationships_created": "relationshipsCreated",
            "files_processed": "filesProcessed",
            "classes_extracted": "classesExtracted",
            "functions_extracted": "functionsExtracted",
        }
        for attr, key in _ATTR_MAP.items():
            val = getattr(result, attr, None)
            if val is not None:
                meta[key] = val

    return meta


def _get_version() -> str:
    """Return the installed opentraceai version."""
    try:
        from importlib.metadata import version

        return version("opentraceai")
    except Exception:
        return "unknown"


@app.command()
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option(
    "--output",
    "output_format",
    type=click.Choice(["text", "json"]),
    default="text",
    show_default=True,
    help="Output format.",
)
def stats(db_path: str | None, output_format: str) -> None:
    """Display graph statistics."""
    import json

    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path, must_exist=True)
    store = GraphStore(resolved_db, read_only=True)
    try:
        data = store.get_stats()
        metadata = store.get_metadata()
    finally:
        store.close()

    if metadata:
        data["metadata"] = metadata

    if output_format == "json":
        click.echo(json.dumps(data))
        return

    # text: compact, prompt-friendly format
    nodes_by_type = data.get("nodes_by_type", {})
    parts = [f"{count} {ntype}" for ntype, count in sorted(nodes_by_type.items(), key=lambda x: -x[1])]
    click.echo(f"{data['total_nodes']} nodes, {data['total_edges']} edges: {', '.join(parts)}")

    for entry in metadata:
        repo_id = entry.get("repoId", "")
        commit_sha = entry.get("commitSha", "")
        commit = commit_sha[:8] if commit_sha else ""
        branch = entry.get("branch", "")
        indexed_at = entry.get("indexedAt", "")
        duration = entry.get("durationSeconds", "")
        ref = f"{branch}@{commit}" if branch and commit else commit or branch
        parts = []
        if repo_id:
            parts.append(repo_id)
        if ref:
            parts.append(ref)
        if indexed_at:
            parts.append(indexed_at)
        if duration:
            parts.append(f"{duration}s")
        if parts:
            click.echo(f"  Indexed: {', '.join(parts)}")


class _ReloadableStore:
    """Transparent proxy for GraphStore that reopens when the DB file is replaced.

    LadybugDB uses exclusive file locking, so a long-running reader (MCP)
    blocks writers (``opentrace index``).  The indexer works around this by
    writing to a staging file and atomically renaming it over the original.

    This proxy detects the rename (via inode change) and transparently
    reopens the database.  Attribute access is delegated to the inner
    store, so callers treat this as a regular ``GraphStore``.
    """

    def __init__(self, db_path: str | None, store: object | None) -> None:
        self._db_path = db_path
        self._store = store
        self._inode = self._stat_inode()
        self._lock = threading.Lock()
        self._log = logging.getLogger("opentrace_agent.mcp.reload")

    # -- inode helpers -------------------------------------------------------

    def _stat_inode(self) -> int | None:
        if self._db_path is None:
            return None
        try:
            return os.stat(self._db_path).st_ino
        except OSError:
            return None

    def _maybe_reload(self) -> None:
        """Reopen the database if the file's inode has changed.

        Thread-safe: FastMCP may dispatch tool calls from a thread pool.
        """
        if self._db_path is None:
            return

        with self._lock:
            current_inode = self._stat_inode()
            if current_inode == self._inode:
                return

            self._log.info(
                "Database file changed (inode %s → %s), reopening",
                self._inode,
                current_inode,
            )

            # Close the old store first.  LadybugDB associates a WAL file
            # with the open database; if we tried to open the new file
            # while the old store still holds its WAL open, the new open
            # would fail with a "Database ID does not match" error.
            if self._store is not None:
                try:
                    self._store.close()
                except Exception:
                    pass

            self._store = None
            self._inode = current_inode

            if current_inode is not None:
                from opentrace_agent.store import GraphStore

                try:
                    self._store = GraphStore(self._db_path, read_only=True)
                except Exception as e:
                    self._log.warning("Failed to reopen database: %s", e)

    # -- proxy protocol ------------------------------------------------------

    def __bool__(self) -> bool:
        self._maybe_reload()
        return self._store is not None

    def __getattr__(self, name: str) -> object:
        self._maybe_reload()
        store = self._store
        if store is None:
            raise AttributeError(name)
        return getattr(store, name)

    def close(self) -> None:
        with self._lock:
            if self._store is not None:
                self._store.close()
                self._store = None


@app.command("mcp")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def mcp_cmd(db_path: str | None, verbose: bool) -> None:
    """Start a stdio MCP server exposing graph query tools."""
    _configure_logging(verbose)
    log = logging.getLogger("opentrace_agent.mcp")

    log.debug("MCP server starting (pid=%d)", os.getpid())

    from opentrace_agent.cli.mcp_server import create_mcp_server
    from opentrace_agent.store import GraphStore

    store: GraphStore | None = None

    try:
        resolved_db = _resolve_db(db_path, must_exist=True)
    except click.UsageError:
        log.info("No index found — MCP server will start without a database")
        resolved_db = None

    if resolved_db is not None:
        log.debug("Opening database: %s", resolved_db)
        try:
            store = GraphStore(resolved_db, read_only=True)
        except Exception as e:
            log.warning("Failed to open database: %s — continuing without index", e)
            store = None

    if store is not None:
        stats = store.get_stats()
        log.debug(
            "Database ready: %d nodes, %d edges",
            stats["total_nodes"],
            stats["total_edges"],
        )

    reloadable = _ReloadableStore(resolved_db, store)

    def _shutdown(signum: int, _frame: object) -> None:
        log.debug("Received signal %d, shutting down", signum)
        reloadable.close()
        raise SystemExit(0)

    signal.signal(signal.SIGTERM, _shutdown)

    try:
        server = create_mcp_server(reloadable, db_path=resolved_db)
        log.debug("MCP server running on stdio")
        server.run(transport="stdio")
    except KeyboardInterrupt:
        log.debug("Interrupted")
    except Exception as e:
        log.error("MCP server error: %s", e, exc_info=True)
        raise
    finally:
        reloadable.close()
        log.debug("MCP server stopped")


@app.command()
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option("--host", default="127.0.0.1", show_default=True, help="Bind address.")
@click.option("--port", default=8787, show_default=True, help="Bind port.")
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def serve(db_path: str | None, host: str, port: int, verbose: bool) -> None:
    """Start an HTTP server exposing the graph database.

    Provides a REST API that replaces the in-browser WASM LadybugDB engine,
    allowing the UI to query a server-backed graph store instead.
    """
    import uvicorn

    _configure_logging(verbose)
    log = logging.getLogger("opentrace_agent.serve")

    from opentrace_agent.cli.serve import create_app
    from opentrace_agent.store import GraphStore

    try:
        resolved_db = _resolve_db(db_path, must_exist=True)
    except click.UsageError as e:
        raise SystemExit(str(e))

    log.debug("Opening database: %s", resolved_db)
    store = GraphStore(resolved_db)

    stats = store.get_stats()
    click.echo(f"Database: {resolved_db}")
    click.echo(f"  {stats['total_nodes']} nodes, {stats['total_edges']} edges")
    click.echo(f"Listening on http://{host}:{port}")

    app = create_app(store)

    try:
        uvicorn.run(app, host=host, port=port, log_level="debug" if verbose else "info")
    except KeyboardInterrupt:
        pass
    finally:
        store.close()


@app.command()
@click.argument("pattern")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="OpenTrace database path (auto-detected if omitted).",
)
def augment(pattern: str, db_path: str | None) -> None:
    """Query the graph for context about a search pattern.

    Prints a short human-readable context block (< 50 lines) to stdout.
    Exits 0 with no output when the pattern matches nothing or no index is found.
    """
    from opentrace_agent.cli.augment import run_augment

    try:
        resolved = _resolve_db(db_path, must_exist=True)
    except click.UsageError:
        resolved = None
    run_augment(pattern, resolved)


@app.command("export")
@click.argument("output", default="opentrace.parquet.zip", type=click.Path())
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def export_cmd(output: str, db_path: str | None, verbose: bool) -> None:
    """Export the graph database as a .parquet.zip archive.

    The archive can be imported in the UI or via `opentraceai import`.
    """
    _configure_logging(verbose)

    from opentrace_agent.cli.export_import import export_database
    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path, must_exist=True)
    click.echo(f"Opening database at {resolved_db} ...")
    store = GraphStore(resolved_db, read_only=True)

    try:
        click.echo("Exporting ...")
        data = export_database(store)
    finally:
        store.close()

    out = Path(output)
    out.write_bytes(data)
    size_kb = len(data) / 1024
    click.echo(f"Wrote {out} ({size_kb:.1f} KB)")


@app.command("import")
@click.argument("archive", type=click.Path(exists=True, dir_okay=False, resolve_path=True))
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help=f"Database path (default: ./{OPENTRACE_DIR}/{DB_NAME}).",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def import_cmd(archive: str, db_path: str | None, verbose: bool) -> None:
    """Import a .parquet.zip archive into the graph database.

    Accepts archives exported from the UI or via `opentraceai export`.
    """
    _configure_logging(verbose)

    from opentrace_agent.cli.export_import import import_database
    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path)
    db_dir = Path(resolved_db).parent
    db_dir.mkdir(parents=True, exist_ok=True)
    _ensure_gitignore(db_dir)

    click.echo(f"Opening database at {resolved_db} ...")
    store = GraphStore(resolved_db)

    data = Path(archive).read_bytes()
    click.echo(f"Importing {archive} ({len(data) / 1024:.1f} KB) ...")

    def on_progress(msg: str) -> None:
        click.echo(f"  {msg}")

    try:
        result = import_database(store, data, on_progress=on_progress)
    finally:
        store.close()

    click.echo(
        f"Imported {result['nodes_created']} nodes, "
        f"{result['relationships_created']} relationships "
        f"({result['errors']} errors)"
    )


# ---------------------------------------------------------------------------
# config command group
# ---------------------------------------------------------------------------


def _resolve_config_path() -> Path:
    """Return the config file path, preferring an existing .opentrace/ dir."""
    from opentrace_agent.cli.config import CONFIG_NAME

    ot_dir = _find_opentrace_dir()
    if ot_dir is not None:
        return ot_dir / CONFIG_NAME
    return Path.cwd() / OPENTRACE_DIR / CONFIG_NAME


@app.group()
def config() -> None:
    """Read or write project configuration (.opentrace/config.yaml)."""


@config.command("set")
@click.argument("key", type=click.Choice(["org"]))
@click.argument("value")
def config_set(key: str, value: str) -> None:
    """Set a configuration value.

    \b
    Supported keys:
      org   Organisation ID (org_xxx) or slug (acme_corp)
    """
    from opentrace_agent.cli.config import load_config, save_config

    path = _resolve_config_path()
    data = load_config(path)
    data[key] = value
    save_config(path, data)
    _ensure_gitignore(path.parent)
    click.echo(f"{key}: {value}")


@config.command("get")
@click.argument("key", type=click.Choice(["org"]))
def config_get(key: str) -> None:
    """Get a configuration value."""
    from opentrace_agent.cli.config import load_config

    path = _resolve_config_path()
    data = load_config(path)
    val = data.get(key)
    if val is None:
        raise click.UsageError(f"'{key}' is not set. Run: opentraceai config set {key} <value>")
    click.echo(val)


@config.command("show")
def config_show() -> None:
    """Show all configuration values."""
    from opentrace_agent.cli.config import load_config

    path = _resolve_config_path()
    data = load_config(path)
    if not data:
        click.echo("No configuration set.")
        return
    for k, v in data.items():
        click.echo(f"{k}: {v}")


@config.command("path")
def config_path() -> None:
    """Print the config file path."""
    click.echo(_resolve_config_path())


@app.command()
@click.option("--resolve", is_flag=True, help="Also resolve an org-scoped token from project config.")
def login(resolve: bool) -> None:
    """Log in to api.opentrace.ai via your browser."""
    from opentrace_agent.cli.auth import load_tokens
    from opentrace_agent.cli.auth import login as do_login

    existing = load_tokens()
    if existing and existing.get("access_token"):
        if not click.confirm("Already logged in. Re-authenticate?", default=False):
            return

    click.echo("Opening browser to log in to OpenTrace ...")
    try:
        payload = do_login()
    except TimeoutError:
        raise click.ClickException("Login timed out — no response from browser within 5 minutes.")
    except Exception as exc:
        raise click.ClickException(f"Login failed: {exc}")

    scope = payload.get("scope", "")
    click.echo(f"Logged in to {payload.get('issuer', 'OpenTrace')} (scope: {scope}).")

    if resolve:
        from opentrace_agent.cli.auth import resolve_org_token
        from opentrace_agent.cli.config import find_config, load_config

        ot_dir = _find_opentrace_dir()
        config_path = find_config(ot_dir)
        if config_path is None:
            click.echo("No .opentrace/config.yaml found — skipping org token resolution.")
            return
        config = load_config(config_path)
        org = config.get("org")
        if not org:
            click.echo("No org set in config — skipping org token resolution.")
            return
        try:
            resolve_org_token(org)
            click.echo(f"Org token resolved for '{org}'.")
        except RuntimeError as exc:
            raise click.ClickException(f"Org token resolution failed: {exc}")


@app.command()
def logout() -> None:
    """Log out and remove saved credentials."""
    from opentrace_agent.cli.auth import clear_tokens
    from opentrace_agent.cli.credentials import clear_org_tokens

    cleared_user = clear_tokens()
    org_count = clear_org_tokens()
    if cleared_user or org_count:
        parts = []
        if cleared_user:
            parts.append("user credentials")
        if org_count:
            parts.append(f"{org_count} org token(s)")
        click.echo(f"Logged out. Removed {', '.join(parts)}.")
    else:
        click.echo("Not logged in.")


@app.command()
def whoami() -> None:
    """Show the current authentication status."""
    from opentrace_agent.cli.auth import load_tokens
    from opentrace_agent.cli.config import find_config, load_config
    from opentrace_agent.cli.credentials import load_org_token

    tokens = load_tokens()
    if not tokens:
        click.echo("Not logged in. Run 'opentraceai login' to authenticate.")
        return

    issuer = tokens.get("issuer", "unknown")
    scope = tokens.get("scope", "none")
    access_token = tokens.get("access_token", "")
    token_type = "user (otuat)" if access_token.startswith("otuat_") else "org-scoped (legacy)"
    created = tokens.get("created_at")

    click.echo(f"Issuer:  {issuer}")
    click.echo(f"Type:    {token_type}")
    click.echo(f"Scope:   {scope}")
    if created:
        from datetime import datetime, timezone

        dt = datetime.fromtimestamp(created, tz=timezone.utc)
        click.echo(f"Issued:  {dt:%Y-%m-%d %H:%M:%S UTC}")

    # Show project org context
    ot_dir = _find_opentrace_dir()
    config_path = find_config(ot_dir)
    if config_path is not None:
        config = load_config(config_path)
        org = config.get("org")
        if org:
            org_token = load_org_token(org)
            if org_token:
                click.echo(f"Org:     {org} (token cached)")
            else:
                try:
                    from opentrace_agent.cli.auth import resolve_org_token

                    resolve_org_token(org)
                    click.echo(f"Org:     {org} (token resolved)")
                except RuntimeError as exc:
                    click.echo(f"Org:     {org} (exchange failed: {exc})")


@app.command()
def refresh() -> None:
    """Refresh the access token using the stored refresh token."""
    from opentrace_agent.cli.auth import refresh as do_refresh

    try:
        payload = do_refresh()
    except RuntimeError as exc:
        raise click.ClickException(str(exc))
    except Exception as exc:
        raise click.ClickException(f"Token refresh failed: {exc}")

    expires_in = payload.get("expires_in")
    if expires_in:
        click.echo(f"Token refreshed (expires in {expires_in}s).")
    else:
        click.echo("Token refreshed.")


# ---------------------------------------------------------------------------
# query command
# ---------------------------------------------------------------------------


@app.command()
@click.argument("query_string")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option(
    "-t",
    "--type",
    "query_type",
    type=click.Choice(["cypher", "fts"]),
    default="cypher",
    show_default=True,
    help="Query language: cypher (default) or fts (full-text search).",
)
@click.option(
    "--limit",
    default=100,
    show_default=True,
    help="Maximum rows to return (FTS only).",
)
@click.option(
    "--output",
    "output_format",
    type=click.Choice(["table", "json", "jsonl"]),
    default="table",
    show_default=True,
    help="Output format.",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def query(
    query_string: str,
    db_path: str | None,
    query_type: str,
    limit: int,
    output_format: str,
    verbose: bool,
) -> None:
    """Run a Cypher or full-text search query against the graph database.

    \b
    Examples:
      opentraceai query "MATCH (n:Node) RETURN n.type, count(n)"
      opentraceai query "MATCH (n:Node {type: 'Function'}) RETURN n.name LIMIT 10"
      opentraceai query "parse" --type fts
      opentraceai query "MATCH (a)-[r:RELATES]->(b) RETURN a.name, r.type, b.name LIMIT 5"
      opentraceai query "GraphStore" --type fts --output json
    """
    import json as json_mod
    import time

    _configure_logging(verbose)

    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path, must_exist=True)
    store = GraphStore(resolved_db, read_only=True)

    try:
        t0 = time.monotonic()

        if query_type == "fts":
            rows, columns = _run_fts_query(store, query_string, limit)
        else:
            rows, columns = _run_cypher_query(store, query_string)

        elapsed = time.monotonic() - t0

        if output_format == "json":
            data = [dict(zip(columns, row)) for row in rows]
            click.echo(json_mod.dumps(data, indent=2, default=str))
        elif output_format == "jsonl":
            for row in rows:
                click.echo(json_mod.dumps(dict(zip(columns, row)), default=str))
        else:
            _print_table(columns, rows)

        click.echo(f"\n{len(rows)} row(s) in {elapsed:.3f}s", err=True)
    finally:
        store.close()


def _run_cypher_query(
    store: "GraphStore",  # noqa: F821
    query_string: str,
) -> tuple[list[list], list[str]]:
    """Execute a Cypher query and return (rows, column_names)."""
    result = store._conn.execute(query_string)
    columns = result.get_column_names()
    rows: list[list] = []
    while result.has_next():
        rows.append(result.get_next())
    return rows, columns


def _run_fts_query(
    store: "GraphStore",  # noqa: F821
    query_string: str,
    limit: int,
) -> tuple[list[list], list[str]]:
    """Run an FTS query and return matching nodes with scores."""
    result = store._conn.execute(
        "CALL QUERY_FTS_INDEX('Node', 'node_fts', $query, top := $limit) RETURN node.id, node.name, node.type, score",
        parameters={"query": query_string, "limit": limit},
    )
    columns = ["id", "name", "type", "score"]
    rows: list[list] = []
    while result.has_next():
        rows.append(result.get_next())
    return rows, columns


def _print_table(columns: list[str], rows: list[list]) -> None:
    """Print rows as an aligned text table."""
    if not rows:
        click.echo("(no results)")
        return

    # Stringify all values
    str_rows = [[str(v) for v in row] for row in rows]
    widths = [len(c) for c in columns]
    for row in str_rows:
        for i, val in enumerate(row):
            if i < len(widths):
                widths[i] = max(widths[i], len(val))

    # Header
    header = "  ".join(c.ljust(widths[i]) for i, c in enumerate(columns))
    click.echo(header)
    click.echo("  ".join("─" * w for w in widths))

    # Rows
    for row in str_rows:
        line = "  ".join((row[i] if i < len(row) else "").ljust(widths[i]) for i in range(len(columns)))
        click.echo(line)


@app.command()
@click.argument("file_path")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="OpenTrace database path (auto-detected if omitted).",
)
@click.option(
    "--lines",
    "line_spec",
    default=None,
    help="Comma-separated line ranges, e.g. '10-25,40-60'.",
)
def impact(file_path: str, db_path: str | None, line_spec: str | None) -> None:
    """Analyze the blast radius of changes to a file.

    Finds functions/classes defined in FILE_PATH, then walks incoming
    relationships (CALLS, IMPORTS, DEPENDS_ON) to show what depends on them.
    Exits 0 with no output when the file is not indexed or no index is found.
    """
    from opentrace_agent.cli.impact import run_impact

    try:
        resolved = _resolve_db(db_path, must_exist=True)
    except click.UsageError:
        resolved = None

    line_ranges: list[tuple[int, int]] | None = None
    if line_spec:
        line_ranges = []
        for part in line_spec.split(","):
            part = part.strip()
            if not part:
                continue
            try:
                if "-" in part:
                    lo, hi = part.split("-", 1)
                    line_ranges.append((int(lo), int(hi)))
                else:
                    n = int(part)
                    line_ranges.append((n, n))
            except ValueError:
                continue

    run_impact(file_path, resolved, line_ranges)


@app.command()
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="OpenTrace database path (auto-detected if omitted).",
)
@click.option(
    "--staged",
    "staged_only",
    is_flag=True,
    default=False,
    help="Only analyze changes staged in the index, ignoring unstaged work.",
)
def diff(db_path: str | None, staged_only: bool) -> None:
    """Run impact analysis on every uncommitted code file.

    Discovers files changed in the working tree (or the index, with
    ``--staged``) via ``git diff --name-only`` and prints the blast radius
    for each. Exits 0 with no output when there are no changes or no index.
    """
    from opentrace_agent.cli.diff import run_diff

    try:
        resolved = _resolve_db(db_path, must_exist=True)
    except click.UsageError:
        resolved = None

    run_diff(os.getcwd(), resolved, staged_only=staged_only)


def _do_clone(
    repo_url: str,
    clone_dir: Path,
    ref: str | None,
) -> Path:
    """Clone ``repo_url`` into ``clone_dir`` and return the final path.

    Tries ``GitCloner`` first (used by the rest of the indexing pipeline)
    then falls back to ``git clone`` if the helper is unavailable.  Only
    public repositories are supported in the open-source build.
    """
    click.echo(f"Cloning {repo_url} ...")
    try:
        from opentrace_agent.sources.code.git_cloner import GitCloner

        cloner = GitCloner()
        kwargs: dict[str, object] = {"dest": clone_dir}
        if ref:
            kwargs["ref"] = ref
        return cloner.clone(repo_url, **kwargs)
    except ImportError:
        pass
    except Exception as e:
        raise click.ClickException(f"Clone failed: {e}")

    import subprocess

    cmd = ["git", "clone", "--depth", "1"]
    if ref:
        cmd.extend(["--branch", ref])
    cmd.extend([repo_url, str(clone_dir)])

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        env={**os.environ, "GIT_TERMINAL_PROMPT": "0"},
    )
    if result.returncode != 0:
        raise click.ClickException(f"git clone failed: {result.stderr}")
    return clone_dir


@app.command("fetch-and-index")
@click.argument("repo_url")
@click.option(
    "--repo-id",
    default=None,
    help="Custom repository ID (defaults to the repo name from the URL).",
)
@click.option("--ref", default=None, help="Branch or tag to clone (defaults to repo HEAD).")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help=f"Database path (default: ./{OPENTRACE_DIR}/{DB_NAME}).",
)
@click.option("--batch-size", default=200, show_default=True, help="Items per batch.")
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def fetch_and_index(
    repo_url: str,
    repo_id: str | None,
    ref: str | None,
    db_path: str | None,
    batch_size: int,
    verbose: bool,
) -> None:
    """Clone REPO_URL and index it into the graph.

    Performs a shallow clone into ``~/.opentrace/repos/{org}/{name}/``,
    then runs the full indexing pipeline.  The clone is kept so
    ``source_read`` can serve files from it later.

    Only public repositories are supported in the open-source build.
    """
    _configure_logging(verbose)

    from opentrace_agent.pipeline import PipelineInput, run_pipeline
    from opentrace_agent.pipeline.adapters import GraphStoreAdapter
    from opentrace_agent.store import GraphStore

    url_parts = repo_url.rstrip("/").split("/")
    inferred_name = url_parts[-1].removesuffix(".git") if url_parts else "repo"
    effective_repo_id = repo_id or inferred_name
    org = url_parts[-2] if len(url_parts) >= 2 else "unknown"

    repos_dir = Path.home() / ".opentrace" / "repos" / org
    repos_dir.mkdir(parents=True, exist_ok=True)
    clone_dir = repos_dir / inferred_name

    if clone_dir.exists() and (clone_dir / ".git").exists():
        click.echo(f"Repository already cloned at {clone_dir}, pulling latest ...")
        try:
            import subprocess

            subprocess.run(
                ["git", "-C", str(clone_dir), "pull", "--ff-only"],
                capture_output=True,
                timeout=60,
            )
        except Exception:
            pass
        local_path = clone_dir
    elif clone_dir.exists():
        import shutil

        shutil.rmtree(clone_dir)
        clone_dir.mkdir(parents=True, exist_ok=True)
        local_path = _do_clone(repo_url, clone_dir, ref)
    else:
        clone_dir.mkdir(parents=True, exist_ok=True)
        local_path = _do_clone(repo_url, clone_dir, ref)

    click.echo(f"Cloned to {local_path}")

    resolved_db = _resolve_db(db_path)
    db_dir = Path(resolved_db).parent
    db_dir.mkdir(parents=True, exist_ok=True)
    _ensure_gitignore(db_dir)

    click.echo(f"Opening database at {resolved_db} ...")
    with GraphStore(resolved_db) as graph_store:
        store = GraphStoreAdapter(graph_store, batch_size=batch_size)

        click.echo(f"Indexing {local_path} as '{effective_repo_id}' ...")
        t0 = time.monotonic()

        inp = PipelineInput(path=str(local_path), repo_id=effective_repo_id)

        last_result = None
        for event in run_pipeline(inp, store=store):
            _print_event(event, verbose)
            if getattr(event, "result", None) is not None:
                last_result = event.result

        elapsed = time.monotonic() - t0

        metadata = _collect_metadata(local_path, effective_repo_id, elapsed, last_result)
        metadata["sourceUri"] = repo_url
        graph_store.save_metadata(metadata)

        store.flush()

    click.echo(f"Done in {elapsed:.1f}s. Repository '{effective_repo_id}' is now indexed.")


def _configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(levelname)s %(name)s: %(message)s",
    )
