# Copyright 2026 OpenTrace Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""OpenTrace CLI — index local codebases into a LadybugDB knowledge graph."""

from __future__ import annotations

import logging
import signal
import time
from pathlib import Path

import click

# ---------------------------------------------------------------------------
# Database discovery
# ---------------------------------------------------------------------------

DB_NAME = "index.db"
OPENTRACE_DIR = ".opentrace"
_MAX_WALK_DEPTH = 10


def _find_git_root(start: Path) -> Path | None:
    """Find the nearest git repo root at or above *start*."""
    current = start.resolve()
    for _ in range(_MAX_WALK_DEPTH):
        if (current / ".git").exists():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    return None


def _is_under(path: Path, root: Path) -> bool:
    """Check if *path* is at or under *root*."""
    try:
        path.relative_to(root)
        return True
    except ValueError:
        return False


def find_db(start: Path | None = None) -> Path | None:
    """Walk up from *start* looking for ``.opentrace/index.db``.

    Security boundaries:
    - Stops at the git repo root (or filesystem root).
    - Rejects symlinks that resolve outside the boundary.
    - Caps upward traversal at ``_MAX_WALK_DEPTH`` levels.
    """
    if start is None:
        start = Path.cwd()
    start = start.resolve()

    git_root = _find_git_root(start)
    # Use git root as boundary only if start is inside it.
    boundary = git_root if git_root and _is_under(start, git_root) else Path(start.anchor)

    current = start
    for _ in range(_MAX_WALK_DEPTH):
        candidate = current / OPENTRACE_DIR / DB_NAME
        if candidate.exists():
            resolved = candidate.resolve()
            # Reject if the resolved path escapes the repo boundary.
            if _is_under(resolved, boundary):
                return resolved
        # Stop at boundary or filesystem root.
        if current == boundary or current.parent == current:
            break
        current = current.parent

    return None


def _resolve_db(db_path: str | None, *, must_exist: bool = False) -> str:
    """Return a database path from an explicit flag or auto-discovery.

    Raises ``click.UsageError`` if *must_exist* and no database is found.
    """
    if db_path is not None:
        p = Path(db_path)
        if must_exist and not p.exists():
            raise click.UsageError(f"Database not found: {db_path}")
        return str(p)

    found = find_db()
    if found is not None:
        return str(found)

    if must_exist:
        raise click.UsageError(
            f"No {OPENTRACE_DIR}/{DB_NAME} found. Run 'opentraceai index' first or pass --db explicitly."
        )

    # Default for index (write) — create in cwd.
    return str(Path.cwd() / OPENTRACE_DIR / DB_NAME)


_GITIGNORE_CONTENT = """\
# OpenTrace index data — generated by `opentraceai index`
*.db
*.db.wal
"""


def _ensure_gitignore(directory: Path) -> None:
    """Write a .gitignore into *directory* if one doesn't already exist."""
    gi = directory / ".gitignore"
    if not gi.exists():
        gi.write_text(_GITIGNORE_CONTENT)


@click.group(invoke_without_command=True)
@click.version_option(package_name="opentraceai")
@click.pass_context
def app(ctx: click.Context) -> None:
    """OpenTrace — map codebases into a knowledge graph."""
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


@app.command()
@click.argument("path", default=".", type=click.Path(exists=True, file_okay=False, resolve_path=True))
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help=f"Database path (default: ./{OPENTRACE_DIR}/{DB_NAME}).",
)
@click.option("--repo-id", default=None, help="Repository ID (defaults to directory name).")
@click.option("--batch-size", default=200, show_default=True, help="Items per batch.")
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def index(
    path: str,
    db_path: str | None,
    repo_id: str | None,
    batch_size: int,
    verbose: bool,
) -> None:
    """Index a local codebase into a LadybugDB knowledge graph."""
    _configure_logging(verbose)

    from opentrace_agent.pipeline import PipelineInput, run_pipeline
    from opentrace_agent.pipeline.adapters import GraphStoreAdapter
    from opentrace_agent.store import GraphStore

    root = Path(path)
    if repo_id is None:
        repo_id = root.name

    resolved_db = _resolve_db(db_path)
    db_dir = Path(resolved_db).parent
    db_dir.mkdir(parents=True, exist_ok=True)
    _ensure_gitignore(db_dir)

    click.echo(f"Opening database at {resolved_db} ...")
    graph_store = GraphStore(resolved_db)
    store = GraphStoreAdapter(graph_store, batch_size=batch_size)

    click.echo(f"Indexing {root} ...")
    t0 = time.monotonic()

    inp = PipelineInput(path=str(root), repo_id=repo_id)

    for event in run_pipeline(inp, store=store):
        _print_event(event, verbose)

    store.close()

    elapsed = time.monotonic() - t0
    click.echo(f"Done in {elapsed:.1f}s.")


def _print_event(event: object, verbose: bool) -> None:
    """Print pipeline events to the terminal."""
    from opentrace_agent.pipeline import EventKind

    kind = getattr(event, "kind", None)
    message = getattr(event, "message", "")
    result = getattr(event, "result", None)

    if kind == EventKind.STAGE_START:
        click.echo(f"  {message}")
    elif kind == EventKind.STAGE_PROGRESS and verbose:
        detail = getattr(event, "detail", None)
        if detail:
            click.echo(f"    [{detail.current}/{detail.total}] {message}")
    elif kind == EventKind.STAGE_STOP:
        click.echo(f"  {message}")
    elif kind == EventKind.DONE and result:
        click.echo(
            f"  {result.nodes_created} nodes, "
            f"{result.relationships_created} relationships, "
            f"{result.files_processed} files, "
            f"{result.classes_extracted} classes, "
            f"{result.functions_extracted} functions"
        )
    elif kind == EventKind.ERROR:
        errors = getattr(event, "errors", [])
        click.echo(f"  Error: {message}", err=True)
        for err in errors or []:
            click.echo(f"    {err}", err=True)


@app.command()
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option(
    "--output",
    "output_format",
    type=click.Choice(["text", "json"]),
    default="text",
    show_default=True,
    help="Output format.",
)
def stats(db_path: str | None, output_format: str) -> None:
    """Display graph statistics."""
    import json

    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path, must_exist=True)
    store = GraphStore(resolved_db, read_only=True)
    try:
        data = store.get_stats()
    finally:
        store.close()

    if output_format == "json":
        click.echo(json.dumps(data))
        return

    # text: compact, prompt-friendly format
    nodes_by_type = data.get("nodes_by_type", {})
    parts = [f"{count} {ntype}" for ntype, count in sorted(nodes_by_type.items(), key=lambda x: -x[1])]
    click.echo(f"{data['total_nodes']} nodes, {data['total_edges']} edges: {', '.join(parts)}")


@app.command("mcp")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def mcp_cmd(db_path: str | None, verbose: bool) -> None:
    """Start a stdio MCP server exposing graph query tools."""
    import sys

    _configure_logging(verbose)
    log = logging.getLogger("opentrace_agent.mcp")

    log.debug("MCP server starting (pid=%d)", __import__("os").getpid())

    from opentrace_agent.cli.mcp_server import create_mcp_server
    from opentrace_agent.store import GraphStore

    try:
        resolved_db = _resolve_db(db_path, must_exist=True)
    except click.UsageError as e:
        log.error("Database discovery failed: %s", e)
        print(str(e), file=sys.stderr)
        raise SystemExit(1)

    log.debug("Opening database: %s", resolved_db)
    try:
        store = GraphStore(resolved_db, read_only=True)
    except Exception as e:
        log.error("Failed to open database: %s", e, exc_info=True)
        print(f"Failed to open database: {e}", file=sys.stderr)
        raise SystemExit(1)

    stats = store.get_stats()
    log.debug(
        "Database ready: %d nodes, %d edges",
        stats["total_nodes"],
        stats["total_edges"],
    )

    def _shutdown(signum: int, _frame: object) -> None:
        log.debug("Received signal %d, shutting down", signum)
        store.close()
        raise SystemExit(0)

    signal.signal(signal.SIGTERM, _shutdown)

    try:
        server = create_mcp_server(store)
        log.debug("MCP server running on stdio")
        server.run(transport="stdio")
    except KeyboardInterrupt:
        log.debug("Interrupted")
    except Exception as e:
        log.error("MCP server error: %s", e, exc_info=True)
        raise
    finally:
        store.close()
        log.debug("MCP server stopped")


@app.command()
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option("--host", default="127.0.0.1", show_default=True, help="Bind address.")
@click.option("--port", default=8787, show_default=True, help="Bind port.")
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def serve(db_path: str | None, host: str, port: int, verbose: bool) -> None:
    """Start an HTTP server exposing the graph database.

    Provides a REST API that replaces the in-browser WASM LadybugDB engine,
    allowing the UI to query a server-backed graph store instead.
    """
    import uvicorn

    _configure_logging(verbose)
    log = logging.getLogger("opentrace_agent.serve")

    from opentrace_agent.cli.serve import create_app
    from opentrace_agent.store import GraphStore

    try:
        resolved_db = _resolve_db(db_path, must_exist=True)
    except click.UsageError as e:
        raise SystemExit(str(e))

    log.debug("Opening database: %s", resolved_db)
    store = GraphStore(resolved_db)

    stats = store.get_stats()
    click.echo(f"Database: {resolved_db}")
    click.echo(f"  {stats['total_nodes']} nodes, {stats['total_edges']} edges")
    click.echo(f"Listening on http://{host}:{port}")

    app = create_app(store)

    try:
        uvicorn.run(app, host=host, port=port, log_level="debug" if verbose else "info")
    except KeyboardInterrupt:
        pass
    finally:
        store.close()


@app.command()
@click.argument("pattern")
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="OpenTrace database path (auto-detected if omitted).",
)
def augment(pattern: str, db_path: str | None) -> None:
    """Query the graph for context about a search pattern.

    Prints a short human-readable context block (< 50 lines) to stdout.
    Exits 0 with no output when the pattern matches nothing or no index is found.
    """
    from opentrace_agent.cli.augment import run_augment

    try:
        resolved = _resolve_db(db_path, must_exist=True)
    except click.UsageError:
        resolved = None
    run_augment(pattern, resolved)


@app.command("export")
@click.argument("output", default="opentrace.parquet.zip", type=click.Path())
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help="Database path (auto-discovered if omitted).",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def export_cmd(output: str, db_path: str | None, verbose: bool) -> None:
    """Export the graph database as a .parquet.zip archive.

    The archive can be imported in the UI or via `opentraceai import`.
    """
    _configure_logging(verbose)

    from opentrace_agent.cli.export_import import export_database
    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path, must_exist=True)
    click.echo(f"Opening database at {resolved_db} ...")
    store = GraphStore(resolved_db, read_only=True)

    try:
        click.echo("Exporting ...")
        data = export_database(store)
    finally:
        store.close()

    out = Path(output)
    out.write_bytes(data)
    size_kb = len(data) / 1024
    click.echo(f"Wrote {out} ({size_kb:.1f} KB)")


@app.command("import")
@click.argument("archive", type=click.Path(exists=True, dir_okay=False, resolve_path=True))
@click.option(
    "--db",
    "db_path",
    default=None,
    type=click.Path(),
    help=f"Database path (default: ./{OPENTRACE_DIR}/{DB_NAME}).",
)
@click.option("-v", "--verbose", is_flag=True, help="Enable debug logging.")
def import_cmd(archive: str, db_path: str | None, verbose: bool) -> None:
    """Import a .parquet.zip archive into the graph database.

    Accepts archives exported from the UI or via `opentraceai export`.
    """
    _configure_logging(verbose)

    from opentrace_agent.cli.export_import import import_database
    from opentrace_agent.store import GraphStore

    resolved_db = _resolve_db(db_path)
    db_dir = Path(resolved_db).parent
    db_dir.mkdir(parents=True, exist_ok=True)
    _ensure_gitignore(db_dir)

    click.echo(f"Opening database at {resolved_db} ...")
    store = GraphStore(resolved_db)

    data = Path(archive).read_bytes()
    click.echo(f"Importing {archive} ({len(data) / 1024:.1f} KB) ...")

    def on_progress(msg: str) -> None:
        click.echo(f"  {msg}")

    try:
        result = import_database(store, data, on_progress=on_progress)
    finally:
        store.close()

    click.echo(
        f"Imported {result['nodes_created']} nodes, "
        f"{result['relationships_created']} relationships "
        f"({result['errors']} errors)"
    )


# ---------------------------------------------------------------------------
# config command group
# ---------------------------------------------------------------------------


def _find_opentrace_dir(start: Path | None = None) -> Path | None:
    """Walk up from *start* looking for an existing ``.opentrace/`` directory.

    Uses the same security boundaries as :func:`find_db`.
    """
    if start is None:
        start = Path.cwd()
    start = start.resolve()

    git_root = _find_git_root(start)
    boundary = git_root if git_root and _is_under(start, git_root) else Path(start.anchor)

    current = start
    for _ in range(_MAX_WALK_DEPTH):
        candidate = current / OPENTRACE_DIR
        if candidate.is_dir():
            resolved = candidate.resolve()
            if _is_under(resolved, boundary):
                return resolved
        if current == boundary or current.parent == current:
            break
        current = current.parent

    return None


def _resolve_config_path() -> Path:
    """Return the config file path, preferring an existing .opentrace/ dir."""
    from opentrace_agent.cli.config import CONFIG_NAME

    ot_dir = _find_opentrace_dir()
    if ot_dir is not None:
        return ot_dir / CONFIG_NAME
    return Path.cwd() / OPENTRACE_DIR / CONFIG_NAME


@app.group()
def config() -> None:
    """Read or write project configuration (.opentrace/config.yaml)."""


@config.command("set")
@click.argument("key", type=click.Choice(["org"]))
@click.argument("value")
def config_set(key: str, value: str) -> None:
    """Set a configuration value.

    \b
    Supported keys:
      org   Organisation ID (org_xxx) or slug (acme_corp)
    """
    from opentrace_agent.cli.config import load_config, save_config

    path = _resolve_config_path()
    data = load_config(path)
    data[key] = value
    save_config(path, data)
    _ensure_gitignore(path.parent)
    click.echo(f"{key}: {value}")


@config.command("get")
@click.argument("key", type=click.Choice(["org"]))
def config_get(key: str) -> None:
    """Get a configuration value."""
    from opentrace_agent.cli.config import load_config

    path = _resolve_config_path()
    data = load_config(path)
    val = data.get(key)
    if val is None:
        raise click.UsageError(f"'{key}' is not set. Run: opentraceai config set {key} <value>")
    click.echo(val)


@config.command("show")
def config_show() -> None:
    """Show all configuration values."""
    from opentrace_agent.cli.config import load_config

    path = _resolve_config_path()
    data = load_config(path)
    if not data:
        click.echo("No configuration set.")
        return
    for k, v in data.items():
        click.echo(f"{k}: {v}")


@config.command("path")
def config_path() -> None:
    """Print the config file path."""
    click.echo(_resolve_config_path())


def _configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.WARNING
    logging.basicConfig(
        level=level,
        format="%(levelname)s %(name)s: %(message)s",
    )
