# Copyright 2026 OpenTrace Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Vault path resolution + path-traversal validation."""

from __future__ import annotations

import os
import re
import shutil
from pathlib import Path

VAULT_NAME_RE = re.compile(r"^[a-zA-Z0-9._-]{1,64}$")
DEFAULT_VAULT_ROOT = Path.home() / ".opentrace" / "vaults"


class InvalidVaultName(ValueError):
    pass


def vault_root(override: Path | str | None = None) -> Path:
    """Return the root directory under which all vaults live."""
    if override is not None:
        return Path(override).expanduser().resolve()
    env = os.environ.get("OT_VAULT_ROOT")
    if env:
        return Path(env).expanduser().resolve()
    return DEFAULT_VAULT_ROOT.resolve()


def validate_vault_name(name: str) -> str:
    """Validate a vault name. Reject empty, too long, traversal, special chars."""
    if not name or name in (".", ".."):
        raise InvalidVaultName(f"invalid vault name: {name!r}")
    if not VAULT_NAME_RE.match(name):
        raise InvalidVaultName(f"vault name must match {VAULT_NAME_RE.pattern}, got {name!r}")
    return name


def vault_dir(name: str, root: Path | str | None = None) -> Path:
    """Return the on-disk path for a named vault, asserting it stays under the root."""
    name = validate_vault_name(name)
    root_path = vault_root(root)
    candidate = (root_path / name).resolve()
    try:
        candidate.relative_to(root_path)
    except ValueError as e:
        raise InvalidVaultName(f"vault path escapes root: {candidate}") from e
    return candidate


def pages_dir(name: str, root: Path | str | None = None) -> Path:
    return vault_dir(name, root) / "pages"


def metadata_path(name: str, root: Path | str | None = None) -> Path:
    return vault_dir(name, root) / ".vault.json"


def compile_log_dir(name: str, root: Path | str | None = None) -> Path:
    return vault_dir(name, root) / ".compile-log"


_VAULT_ROOT_GITIGNORE = """\
# OpenTrace vault data — generated by `opentraceai wiki compile`.
# Lock files and per-compile audit logs are noise; the actual pages and
# metadata can be version-controlled if desired.
*.lock
.compile-log/
"""


def _ensure_vault_root_gitignore(root: Path) -> None:
    """Write a ``.gitignore`` into the vault root if one doesn't already exist.

    Mostly defensive: vaults usually live in ``~/.opentrace/`` outside any
    repo. But if a user opts into ``OT_VAULT_ROOT=./.opentrace/vaults``
    inside a project, this keeps ``.lock`` files and the audit logs out of
    their git status.
    """
    gi = root / ".gitignore"
    if not gi.exists():
        gi.write_text(_VAULT_ROOT_GITIGNORE)


def ensure_vault_layout(name: str, root: Path | str | None = None) -> Path:
    """Create the vault directory layout (pages/, .compile-log/) if missing."""
    root_path = vault_root(root)
    root_path.mkdir(parents=True, exist_ok=True)
    _ensure_vault_root_gitignore(root_path)
    vd = vault_dir(name, root)
    vd.mkdir(parents=True, exist_ok=True)
    (vd / "pages").mkdir(exist_ok=True)
    (vd / ".compile-log").mkdir(exist_ok=True)
    return vd


def delete_vault(name: str, root: Path | str | None = None) -> bool:
    """Recursively delete the vault directory for *name*.

    Returns ``True`` if a directory existed and was removed, ``False`` if
    no such vault was present. Validates *name* via :func:`vault_dir` so
    the path can never escape the configured vault root.
    """
    vd = vault_dir(name, root)
    if not vd.exists():
        return False
    if not vd.is_dir():
        return False
    shutil.rmtree(vd)
    return True


def list_vaults(root: Path | str | None = None) -> list[str]:
    """Return names of compiled vaults under *root*.

    A directory only counts as a "vault" once it has a ``.vault.json`` —
    so a compile that errored before reaching the Persist stage doesn't
    leave an empty placeholder cluttering the sidebar.
    """
    root_path = vault_root(root)
    if not root_path.exists():
        return []
    out: list[str] = []
    for entry in sorted(root_path.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        try:
            validate_vault_name(entry.name)
        except InvalidVaultName:
            continue
        if not (entry / ".vault.json").exists():
            continue
        out.append(entry.name)
    return out
