name: License Header Check

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check license headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Check license headers
        uses: apache/skywalking-eyes/header@a050f6cbb9a922bf1d8243219221959edc2bfda6 # v0.8.0
        with:
          mode: check
